### PR TITLE
WIP refactor to account for core changes to asset initialisation

### PR DESCRIPTION
**Pull request by merefield**

### CODE REVIEW

**Comment by angusmcleod** [comment]
@merefield I'm getting an exception after clicking "Done" in the location modal.

Screen Shot 2020-06-03 at 8 31 15 AM

**Comment by merefield** [comment]
> @merefield I'm getting an exception after clicking "Done" in the location modal.
> 
> Screen Shot 2020-06-03 at 8 31 15 AM

Thanks I'll take a look in the morning and revert.

**Comment by lumi-89** [comment]
I'm getting an error in the user profile, when a custom location format is set. Apparently there's a self.site.country_codes instead of this.site.country_codes [here](https://github.com/paviliondev/discourse-locations/pull/50/commits/af312e913f2da5531f6512784fbce2799919d9f2#diff-a64daa8e77281c76740a4aeb5d5a5b06R30) in the last commit.

**Comment by merefield** [comment]
Hi lumi, this was part of the refactor to grab at the settings object which is no longer at `Discourse`.  Can you give me a more detailed set of instructions to reproduce please?  Did you upgrade before Monday?

**Comment by lumi-89** [comment]
I upgraded just today (been following the work on the refactor). How to reproduce:

1) set 'location user profile format' in the plugin options (in our case city, country)
2) add a geocoded location in the user profile (settings -> profile -> location)
3) the location display on the user profile page breaks

Here's the error I get in the console:
kuva
It can be traced to the line I linked above ([this one](https://github.com/paviliondev/discourse-locations/pull/50/commits/af312e913f2da5531f6512784fbce2799919d9f2#diff-a64daa8e77281c76740a4aeb5d5a5b06R30)). I can make a pull request for this if you wish, but it's a one line fix.

**Comment by merefield** [comment]
Please DON'T upgrade outside 1st-5th day of the month, we don't have the bandwidth to support and are now busy with client work.  I will try this out though.

**Comment by lumi-89** [comment]
Thanks! I didn't know there was no support for bugfixes outside a set time window. We upgraded our forum first on May 31st, only to find the plugin completely broken. I kept an eye on this fork and notified our admins the moment it was merged to master (I don't have credentials to make upgrades myself). Unfortunately the upgrade was delayed until today. Perhaps we should maintain our own fork, because our update interval is rather irregular.

**Comment by merefield** [comment]
We are considering a paid option for client support outside this window.  If interested contact us at https://thepavilion.io

**Pull request merged**
