### PR TITLE
UX: open user card on map avatar click

### PR DESCRIPTION
**Pull request by renato**
For user avatars, use an `<a>` element so it can open with a ctrl-click and delegate the user card handling via `data-user-card`.

The avatar marker inline styles were extracted to the existing classes.

I kept the support to a missing `rawMarker.options.routeTo` but I'm not sure if we ever hit this scenario.

https://github.com/paviliondev/discourse-locations/assets/3530/8cb29532-3abc-42bc-9a2e-d65451b498e8

### CODE REVIEW

**Comment by merefield** [comment]
@renato great start, thanks.

However there are two issues with this:

* this new behaviour needs to be behind a setting, so admin has choice of old behaviour
* TRICKIER: the map button on the User Card doesn't work - I'd be ok if in this special scenario the button was hidden, but you will need to add logic to action that such that it needs to know it was launched from the map ...

Can you please take a look at those?

**Comment by merefield** [comment]
@renato this looks great!  Yeah, I'm not sure the best way to do this, but your solution is functional.  So tricky integrating third party libraries sometimes and you have to revert to dom queries ... anyway ... 

The only thing I'd say here is it would be _ideal_ if we had some QUnit front end tests (since Locations uses QUnit) to capture the User Map loading, an example User marker or two appearing, and the User Card appearing after a click (and with no map button!).

If you don't have the capacity to do that, that's ok and I will add.

**Comment by renato** [comment]
Hey @merefield, sorry for not getting back to you! I was planning to add those tests but I didn't find the time to do so. Thanks for merging it!

**Comment by merefield** [comment]
I'll look to add them at some point.

**Pull request merged**
