### PR TITLE
COMPATBILITY: resolve issues with old style actions whilst updating affected files to modern standards

### PR DESCRIPTION
**Pull request by merefield**

### CODE REVIEW

**Comment by angusmcleod** [comment]
Looks good, albeit in my PR I didn't do the conversion to modern components yet as I'll be doing that in batch when I integrated the events integration plugin.

**Comment by angusmcleod** [comment]
@merefield Country selection doesn't seem to be working?

Screenshot 2022-11-21 at 12 17 44

**Comment by merefield** [comment]
Ha, good catch, actually was already looking at that and had reverted to draft.  Investigating

**Comment by merefield** [comment]
ok that (and other issues I found) should be resolved.

**Comment by angusmcleod** [comment]
@merefield Looks good!

**Pull request merged**
